# Generated by Django 3.1.2 on 2020-10-06 21:30

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('amenity', models.CharField(choices=[('restaurant', 'restaurant'), ('fast_food', 'fast food'), ('cafe', 'cafe')], max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('website', models.CharField(max_length=254, null=True)),
                ('cuisine', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
