# Generated by Django 3.1.2 on 2020-10-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='name',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
