version: '3.8'

services:
  db:
    image: postgis/postgis:12-3.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
    volumes:
      - "/var/lib/postgresql/explore:/var/lib/postgresql/data"

  web:
    build: .
    command: gunicorn --certfile=/etc/certs/${CERT_FILE} --keyfile=/etc/certs/${CERT_KEY_FILE} geodjango.wsgi -b 0.0.0.0:443
    volumes:
      - .:/code
      - ${CERT_DIR}:/etc/certs
    expose:
      - "443"
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    container_name: ng
    environment:
      NGINX_HOST: ${EXTERNAL_HOST}
      CERT_FILE: ${CERT_FILE}
      CERT_KEY_FILE: ${CERT_KEY_FILE}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ${CERT_DIR}:/etc/certs
    depends_on:
      - web
