version: '3.8'

services:
  db:
    image: postgis/postgis:12-3.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}

  web:
    build: .
    command: gunicorn --certfile=/etc/certs/live/${EXTERNAL_HOST}/fullchain.pem --keyfile=/etc/certs/live/${EXTERNAL_HOST}/privkey.pem geodjango.wsgi -b 0.0.0.0:443 
    volumes:
      - .:/code
      - /etc/letsencrypt:/etc/certs
    expose:
      - "443"
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    container_name: ng
    environment:
      NGINX_HOST: ${EXTERNAL_HOST}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web
