version: '3.8'

services:
  db:
    image: postgis/postgis:12-3.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}

  web:
    build: .
    command: gunicorn --certfile=/etc/certs/localhost.crt --keyfile=/etc/certs/localhost.key geodjango.wsgi -b 0.0.0.0:8000
    volumes:
      - .:/code
      - ../certs/:/etc/certs/
    expose:
      - "443"
    depends_on:
      - db

  nginx:
    image: nginx:1.19.3
    container_name: ng
    environment:
      NGINX_HOST: ${HOST}
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ../certs/:/etc/nginx/conf.d/certs/
    depends_on:
      - web
